# Generated by Django 2.2.4 on 2019-08-11 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('avaliacao', models.TextField()),
                ('recomendacao', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
